Repository Developer-Student-Clubs-UBa/DSC-UBa-members, pull requests merged in 2021-10, with the labels that each got.

#35 Member updates
  members.json
Labels: hacktoberfest-accepted

#38 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#33 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#39 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#36 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#41 Updated members2021.json file
  members2021.json
Labels: hacktoberfest-accepted

#40 Updated members.json file
  members.json
Labels: invalid, hacktoberfest-accepted

#42 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#44 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#45 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#43 Revert "Update members2021.json"
  members2021.json
Labels: hacktoberfest, hacktoberfest-accepted

#46 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#48 Added my info
  members2021.json
Labels: hacktoberfest-accepted

#50 Update members.json
  members.json
Labels: hacktoberfest-accepted

#49 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#51 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#52 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#54 Update members2021.json
  members2021.json
Labels: hacktoberfest-accepted

#55 Added Joel Fah, id = 14
  members2021.json
Labels: hacktoberfest-accepted
